import { canonicalJson, type BlockRegistry } from '@blockfw/blocks';
import type { ProjectGraph } from '@blockfw/manifest';
import { resolveWiring } from '@blockfw/wiring';
import { hashFiles, type CompileResult } from './compile.js';
import { DATA_CORE } from './data-core.js';
import { WEB_DATA_RUNTIME, DATA_STYLES } from './web-data.js';
import { WEB_RUNTIME, WEB_STYLES } from './web-runtime.js';

/** The standalone web export and the editor preview share this exact runtime. */
export function compileWebProject(graph: ProjectGraph, registry: BlockRegistry): CompileResult {
  const wiring = resolveWiring(graph, registry);
  const hydrated = {
    ...graph,
    blocks: graph.blocks.map((b) => ({
      ...b,
      config: { ...registry.get(b.type).manifest.defaultConfig, ...b.config },
    })),
  };
  const files = [
    {
      path: 'package.json',
      content:
        canonicalJson({
          name: graph.app.slug,
          version: graph.app.version,
          private: true,
          type: 'module',
          scripts: { dev: 'vite', build: 'tsc --noEmit && vite build', preview: 'vite preview' },
          dependencies: { react: '19.2.3', 'react-dom': '19.2.3' },
          devDependencies: {
            vite: '6.3.5',
            typescript: '5.9.3',
            '@types/react': '19.2.3',
            '@types/react-dom': '19.2.3',
          },
        }) + '\n',
    },
    {
      path: 'index.html',
      content:
        '<!doctype html><html lang="en"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0"><title>' +
        graph.app.name.replace(/[&<>"']/g, (c) => '&#' + c.charCodeAt(0) + ';') +
        '</title></head><body><div id="root"></div><script type="module" src="/src/main.tsx"></script></body></html>',
    },
    {
      path: 'tsconfig.json',
      content:
        canonicalJson({
          compilerOptions: {
            target: 'ES2022',
            module: 'ESNext',
            moduleResolution: 'Bundler',
            jsx: 'react-jsx',
            strict: true,
            resolveJsonModule: true,
            esModuleInterop: true,
            skipLibCheck: true,
            lib: ['ES2022', 'DOM', 'DOM.Iterable'],
            noEmit: true,
          },
          include: ['src'],
        }) + '\n',
    },
    { path: 'src/runtime.tsx', content: WEB_RUNTIME },
    { path: 'src/data-core.ts', content: DATA_CORE },
    { path: 'src/data-runtime.tsx', content: WEB_DATA_RUNTIME },
    { path: 'src/styles.css', content: WEB_STYLES + DATA_STYLES },
    { path: 'src/project.json', content: canonicalJson(hydrated) + '\n' },
    { path: 'src/wires.json', content: canonicalJson(wiring.wires) + '\n' },
    {
      path: 'src/main.tsx',
      content:
        "import React from 'react';\nimport { createRoot } from 'react-dom/client';\nimport { Application, type Graph } from './runtime';\nimport graph from './project.json';\nimport wires from './wires.json';\nimport './styles.css';\ncreateRoot(document.getElementById('root')!).render(<Application graph={graph as Graph} wires={wires} />);\n",
    },
    { path: '.gitignore', content: 'node_modules/\ndist/\n*.log\n.env.local\n' },
    {
      path: 'README.md',
      content:
        '# ' +
        graph.app.name +
        '\n\nGenerated by Block Framework for the web.\n\nRun `npm install`, then `npm run dev`. Build with `npm run build`; host the resulting dist directory on any static host. Navigation uses URL hashes and supports browser back/forward.\n\nPages compose ordered blocks; event wires route payloads to consumers. Customize src/runtime.tsx for new block renderers and src/styles.css for styling. project.json and wires.json are the exported contracts.\n\nAuthentication and purchases are local demonstrations. Connect production services before launching. Settings toggles are local state. Google Fonts is optional; system fonts work offline.\n',
    },
  ];
  const projectHash = hashFiles(files);
  files.push({
    path: 'src/wiring-report.json',
    content: canonicalJson({ projectHash, target: 'web', ...wiring.report }) + '\n',
  });
  files.sort((a, b) => a.path.localeCompare(b.path));
  return { files, wiring, projectHash };
}
