import { canonicalJson, type BlockRegistry } from '@blockfw/blocks';
import type { ProjectGraph } from '@blockfw/manifest';
import { resolveWiring } from '@blockfw/wiring';
import { hashFiles, type CompileResult } from './compile.js';
import { DATA_CORE } from './data-core.js';
import { WEB_DATA_RUNTIME, DATA_STYLES } from './web-data.js';
import { WEB_RUNTIME, WEB_STYLES } from './web-runtime.js';
import { CLOUD_RUNTIME, CLOUD_SERVER, CLOUD_SCHEMA, CLOUD_STYLES } from './cloud-assets.js';

/** The standalone web export and the editor preview share this exact runtime. */
export function compileWebProject(graph: ProjectGraph, registry: BlockRegistry): CompileResult {
  if (
    !graph.app.cloud &&
    graph.blocks.some((b) =>
      /^(auth.account|onboarding.profile|billing.plans|account.settings|billing.review)@/.test(
        b.type,
      ),
    )
  )
    throw new Error(
      'Real account blocks need a cloud-enabled app. Create the Cloud notes template or enable Supabase in cloud setup first.',
    );
  const wiring = resolveWiring(graph, registry);
  const hydrated = {
    ...graph,
    blocks: graph.blocks.map((b) => ({
      ...b,
      config: { ...registry.get(b.type).manifest.defaultConfig, ...b.config },
    })),
  };
  const files = [
    {
      path: 'package.json',
      content:
        canonicalJson({
          name: graph.app.slug,
          version: graph.app.version,
          private: true,
          type: 'module',
          scripts: {
            dev: 'vite',
            build: 'tsc --noEmit && vite build',
            preview: 'vite preview',
            ...(graph.app.cloud
              ? {
                  start: 'node --env-file-if-exists=.env server/index.mjs',
                  'check:cloud': 'node --check server/index.mjs',
                }
              : {}),
          },
          engines: { node: '>=22' },
          dependencies: { react: '19.2.3', 'react-dom': '19.2.3', qrcode: '1.5.4' },
          devDependencies: {
            vite: '6.4.4',
            typescript: '5.9.3',
            '@types/react': '19.2.3',
            '@types/react-dom': '19.2.3',
            '@types/qrcode': '1.5.6',
          },
        }) + '\n',
    },
    {
      path: 'index.html',
      content:
        '<!doctype html><html lang="en"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0"><title>' +
        graph.app.name.replace(/[&<>"']/g, (c) => '&#' + c.charCodeAt(0) + ';') +
        '</title></head><body><div id="root"></div><script type="module" src="/src/main.tsx"></script></body></html>',
    },
    {
      path: 'tsconfig.json',
      content:
        canonicalJson({
          compilerOptions: {
            target: 'ES2022',
            module: 'ESNext',
            moduleResolution: 'Bundler',
            jsx: 'react-jsx',
            strict: true,
            resolveJsonModule: true,
            esModuleInterop: true,
            skipLibCheck: true,
            lib: ['ES2022', 'DOM', 'DOM.Iterable'],
            noEmit: true,
          },
          include: ['src'],
        }) + '\n',
    },
    { path: 'src/runtime.tsx', content: WEB_RUNTIME },
    { path: 'src/data-core.ts', content: DATA_CORE },
    { path: 'src/data-runtime.tsx', content: WEB_DATA_RUNTIME },
    { path: 'src/cloud-runtime.tsx', content: CLOUD_RUNTIME },
    { path: 'src/styles.css', content: WEB_STYLES + DATA_STYLES + CLOUD_STYLES },
    { path: 'src/project.json', content: canonicalJson(hydrated) + '\n' },
    { path: 'src/wires.json', content: canonicalJson(wiring.wires) + '\n' },
    {
      path: 'src/main.tsx',
      content:
        "import React from 'react';\nimport { createRoot } from 'react-dom/client';\nimport { Application, type Graph } from './runtime';\nimport graph from './project.json';\nimport wires from './wires.json';\nimport './styles.css';\ncreateRoot(document.getElementById('root')!).render(<Application graph={graph as Graph} wires={wires} />);\n",
    },
    {
      path: '.gitignore',
      content: 'node_modules/\ndist/\n*.log\n.env\n.env.local\n.env.production\n',
    },
    {
      path: 'README.md',
      content:
        '# ' +
        graph.app.name +
        '\n\nGenerated by Block Framework for the web.\n\nRun `npm install`, then `npm run dev`. Build with `npm run build`; host the resulting dist directory on any static host. Navigation uses URL hashes and supports browser back/forward.\n\nPages compose ordered blocks; event wires route payloads to consumers. Customize src/runtime.tsx for new block renderers and src/styles.css for styling. project.json and wires.json are the exported contracts.\n\nAuthentication and purchases are local demonstrations. Connect production services before launching. Settings toggles are local state. Google Fonts is optional; system fonts work offline.\n',
    },
  ];
  if (graph.app.cloud) {
    files.push(
      { path: 'server/index.mjs', content: CLOUD_SERVER },
      { path: 'supabase/migrations/001_paper_cloud.sql', content: CLOUD_SCHEMA },
      {
        path: '.env.example',
        content:
          'APP_ORIGIN=http://127.0.0.1:8787\nPORT=8787\nSUPABASE_URL=\nSUPABASE_ANON_KEY=\nSUPABASE_SERVICE_ROLE_KEY=\nSESSION_ENCRYPTION_KEY=\nOWNER_EMAIL=pdcstmoments@gmail.com\nUPI_ID=9480106354@slc\nPAID_ACCESS_DAYS=30\n# Optional local Studio access (never configure in production)\nSTUDIO_ORIGIN=http://127.0.0.1:5174\n',
      },
      {
        path: 'Dockerfile',
        content:
          'FROM node:24-alpine AS build\nWORKDIR /app\nCOPY package*.json ./\nRUN npm install\nCOPY . .\nRUN npm run build\nFROM node:24-alpine\nWORKDIR /app\nCOPY --from=build /app/dist ./dist\nCOPY --from=build /app/server ./server\nUSER node\nENV HOST=0.0.0.0 PORT=8787\nEXPOSE 8787\nHEALTHCHECK --interval=30s CMD node -e "fetch(\'http://127.0.0.1:8787/healthz\').then(r=>process.exit(r.ok?0:1)).catch(()=>process.exit(1))"\nCMD ["node", "server/index.mjs"]\n',
      },
      { path: '.dockerignore', content: 'node_modules\ndist\n.git\n.env\n.env.*\n' },
      {
        path: 'CLOUD-SETUP.md',
        content:
          "# Real cloud app setup\n\n1. Apply supabase/migrations/001_paper_cloud.sql to a dedicated Supabase project.\n2. Copy .env.example to .env and configure server credentials. Generate SESSION_ENCRYPTION_KEY with `node -e \"console.log(require('node:crypto').randomBytes(32).toString('hex'))\"`. Never publish .env.\n3. In Supabase enable confirmed email/password and Google. Configure Google OAuth with your project callback (`SUPABASE_URL/auth/v1/callback`), then store its client ID and secret in the Supabase provider settings.\n4. Set Supabase Site URL to APP_ORIGIN and allow APP_ORIGIN/auth/callback and APP_ORIGIN/auth/confirm. Keep the default Supabase confirmation and recovery templates. Email flows use PKCE: open the email link in the same browser that initiated signup or recovery. If confirmation was opened elsewhere, return to Paper and sign in with the confirmed email. Restart recovery in the browser where its link will open. Configure production SMTP for public email delivery.\n5. Run npm install, npm run build, and npm start. The backend serves the app and API on one origin. Local Studio can use the backend URL and the explicit loopback STUDIO_ORIGIN.\n6. For hosting, deploy the Dockerfile or run the Node server behind HTTPS. Set APP_ORIGIN to the real HTTPS origin, remove STUDIO_ORIGIN, configure secrets in the host, and test login, email confirmation, recovery, and owner isolation before sharing.\n\nFree: 25 notes. Plus: INR 500 / 1000 notes. Pro: INR 1000 / 10000 notes. Paid passes last PAID_ACCESS_DAYS days, with manual renewal. A personal UPI QR/payment link initiates an actual payment but does not confirm receipt. Users submit references; the verified OWNER_EMAIL account reviews the actual bank receipt and grants access through the owner panel. Repeated approval does not grant twice. This is a manual UPI testing integration, not a merchant-gateway subscription or automatic receipt check.\n\nData is private Supabase PostgreSQL storage. Writes use optimistic revisions, RLS, and server/database plan limits. Expiration keeps notes readable; creating more notes can require an upgrade. Preview against the connected backend writes real cloud data. Canvas thumbnails use temporary preview data only.\n\nNative cloud export is deliberately unavailable until native authentication/session/payment integration is implemented.\n\nOperations: protect the service role and encryption key, retain the encryption key across restarts, back up PostgreSQL, periodically delete expired paper_sessions, monitor /healthz plus authenticated cloud readiness, and configure trusted reverse-proxy rate limiting at the host. Rate limiting inside this single-process server uses socket addresses and does not trust forwarded headers.\n",
      },
    );
    files.find((f) => f.path === 'README.md')!.content =
      '# ' +
      graph.app.name +
      '\n\nReal account-based cloud notes application generated from Block Studio. Follow CLOUD-SETUP.md to configure Supabase, Google, email, UPI verification, and hosting. Run npm install, npm run build, and npm start. Secrets stay on the backend; browser code receives no provider credentials.\n';
  }
  const projectHash = hashFiles(files);
  files.push({
    path: 'src/wiring-report.json',
    content: canonicalJson({ projectHash, target: 'web', ...wiring.report }) + '\n',
  });
  files.sort((a, b) => a.path.localeCompare(b.path));
  return { files, wiring, projectHash };
}
