import type { SpineField, SpineFile, SpineFieldType } from './types.js';

const SQL_TYPES: Record<SpineFieldType, string> = {
  uuid: 'UUID',
  text: 'TEXT',
  int: 'INTEGER',
  bigint: 'BIGINT',
  bool: 'BOOLEAN',
  timestamptz: 'TIMESTAMPTZ',
  date: 'DATE',
  jsonb: 'JSONB',
  numeric: 'NUMERIC',
};

function fieldSql(field: SpineField): string {
  const parts = [`"${field.name}"`, SQL_TYPES[field.type]];
  if (field.primaryKey) parts.push('PRIMARY KEY');
  if (!field.nullable && !field.primaryKey) parts.push('NOT NULL');
  if (field.unique && !field.primaryKey) parts.push('UNIQUE');
  if (field.default) parts.push(`DEFAULT ${field.default}`);
  if (field.references) {
    const onDelete = field.onDelete ?? 'CASCADE';
    // Quote table and column separately: `REFERENCES profiles.id` would be
    // parsed as schema "profiles", table "id" (Postgres 3F000). The
    // parenthesized form is unambiguous.
    const [refTable, refColumn] = (field.references as string).split('.');
    parts.push(`REFERENCES "${refTable}" ("${refColumn}") ON DELETE ${onDelete}`);
  }
  return '  ' + parts.join(' ');
}

/**
 * Generate a PostgreSQL migration from the spine.
 * Deterministic: entities and fields render in file order.
 */
export function spineToSql(spine: SpineFile): string {
  const tables = spine.entities.map((e) => {
    const cols = e.fields.map(fieldSql).join(',\n');
    const comment = e.description ? `-- ${e.description}\n` : '';
    return `${comment}CREATE TABLE IF NOT EXISTS "${e.name}" (\n${cols}\n);`;
  });
  return (
    `-- Generated by Block Framework Entity Spine. Do not edit.\n` +
    `-- Apply with: psql $DATABASE_URL -f migration.sql\n` +
    `-- Or paste into the Supabase dashboard SQL editor.\n\n` +
    tables.join('\n\n') +
    '\n'
  );
}
