import type { SpineField, SpineFile, SpineFieldType } from './types.js';

const TS_TYPES: Record<SpineFieldType, string> = {
  uuid: 'string',
  text: 'string',
  int: 'number',
  bigint: 'number',
  bool: 'boolean',
  timestamptz: 'string',
  date: 'string',
  jsonb: 'unknown',
  numeric: 'number',
};

function tsType(field: SpineField): string {
  const base = TS_TYPES[field.type];
  return field.nullable ? `${base} | null` : base;
}

/**
 * Generate the Supabase-style Database type from the spine.
 * Row: exact DB shape. Insert: fields with defaults/nullable are optional.
 * Update: everything optional. Deterministic: file order, sorted nowhere —
 * the author's order is the contract.
 */
export function spineToTypes(spine: SpineFile): string {
  const tables = spine.entities.map((e) => {
    const rowFields = e.fields
      .map((f) => `        ${JSON.stringify(f.name)}: ${tsType(f)};`)
      .join('\n');
    const insertFields = e.fields
      .map((f) => {
        // Primary keys with defaults are optional on insert; everything
        // nullable or defaulted is optional; the rest is required.
        const opt = f.default !== undefined || f.nullable ? '?' : '';
        return `        ${JSON.stringify(f.name)}${opt}: ${tsType(f)};`;
      })
      .join('\n');
    const updateFields = e.fields
      .map((f) => `        ${JSON.stringify(f.name)}?: ${tsType(f)};`)
      .join('\n');
    return (
      `      ${JSON.stringify(e.name)}: {\n` +
      `        Row: {\n${rowFields}\n        };\n` +
      `        Insert: {\n${insertFields}\n        };\n` +
      `        Update: {\n${updateFields}\n        };\n` +
      `      };`
    );
  });
  return (
    `/**\n` +
    ` * Generated by Block Framework Entity Spine. Do not edit.\n` +
    ` * Regenerate: blockc spine types <spine.json>\n` +
    ` */\n` +
    `export interface Database {\n` +
    `  public: {\n` +
    `    Tables: {\n${tables.join('\n')}\n` +
    `    };\n` +
    `  };\n` +
    `}\n`
  );
}
